### ISSUE TITLE
Need authenticate func

### ISSUE THREAD

**Issue by gtolarc** [greymass/ual-anchor#7]
ual-scatter has the following authenticate implementation:
https://github.com/EOSIO/ual-scatter/blob/master/src/ScatterUser.ts#L111

This is useful when receiving user signup from a centralized server, separate from client-wallet communication.
This is because sending a signature, data, nonce, and publicKey to the server enables data validation with the ecc.recoverHash command.
Can you provide a function to verify the possession of a private key through a signature like this?

**Comment by aaroncox** [comment]
The [login process in ual-anchor](https://github.com/greymass/ual-anchor/blob/master/src/Anchor.ts#L205) does already verify the possession of a private key and return a proof through the use of [identity requests](https://github.com/eosio-eps/EEPs/blob/master/EEPS/eep-7.md#identity-requests) as it uses [anchor-link to call the identify method](https://github.com/greymass/anchor-link/blob/master/src/link.ts#L344-L402). 

The proofs are returned via the callback method, which could also be listened for on a centralized server. 

It doesn't look like we're exposing that proof right now in UAL though, which is returned as `identity` in [this part of ual-anchor](https://github.com/greymass/ual-anchor/blob/master/src/Anchor.ts#L205). We'll add that information to the returned `AnchorUser` object so that other applications can also verify the signature being returned and provide proof of ownership.

**Comment by gtolarc** [comment]
I confirmed that I can get the desired value by returning the login function manually. As you mentioned, it would be really nice to add the return content to the anchorUser object at the login.

**Comment by gtolarc** [comment]
> We'll add that information to the returned `AnchorUser` object so that other applications can also verify the signature being returned and provide proof of ownership.

When can you implement this part? @aaroncox

**Comment by aaroncox** [comment]
Sorry for the delay, we had a few external things impacting us getting back on top of UAL. 

I pushed this up on my priorities list, I'll see if we can get it exposed soon in a new release of ual-anchor.

**Comment by aaroncox** [comment]
Alright, ual-anchor@0.5.1 is published now and does expose the proofs themselves. 

I have also updated our `ual-reactjs-renderer-demo-multipass` repository to include how to verify these proofs, which can be found here: 

https://github.com/greymass/ual-reactjs-renderer-demo-multipass/blob/0c71aec6de6882162ba75db87dbc01efed693bb5/src/Main.js#L33-L51

The proof itself is not persisted and is only available upon initial login, so additional checks are needed to see if the proof exists before validating it.

**Comment by gtolarc** [comment]
thx!! @aaroncox
